### ISSUE TITLE
Read a recommendation

### ISSUE THREAD

**Issue by QihengWang** [nyu-summer2022-devops/recommendations#17]
**As a** user
 **I need** the ability to read recommendations for a product
 **So that** I'm able to to know what products are recommended when I'm buying a specific product.  
   
 ### Details and Assumptions
 * For a user, when I'm browsing a product, the recommendations  for this product should be displayed.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I have the function '' to read recommendations of a product  for a user
 When I call GET read_recommendations/product_id 
 Then recommendations of this product should be shown to the user.
 ```

**Comment by brady800526** [comment]
Does it has similar function with this issue #12 ?

**Comment by rayichiu** [comment]
I'm wondering about this as well and the also the difference between listing all recommendations & read a recommendation. 
I'm not sure if listing all recommendations is **listing all the recommendations for a specific product** or **all the products in the shopping cart**. If it is **listing all the recommendations for a specific product** then reading a recommendation might be the function to look into the detail of a single recommendation.

**Comment by QihengWang** [comment]
My idea is that for **listing all the recommendations**, we should only require a user_id and get all the recommendations for this user, since this user may have bought several products. And for ***reading a recommendation*, the user may click on a specific product to check the details of this product, and we should give the user those recommendations for this specific product that the user clicked.

**Comment by brady800526** [comment]
I think both make senses, as for endpoint, I think Qiheng saying it should be /recommendations/{user_id} to list all recommendations for that specific user. While Rayi saying it should be /recommendations/{product_id} to list upsell products for that product. I think both are fair enough, we can do it all but with different endpoints.
