### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by brady800526** [nyu-summer2022-devops/recommendations#36]
**As a** User/Market Manager
 **I need** Update the README.md file about instructions
 **So that** they can know what calls are available and what inputs they expect and how to run and test your code so that users will know how it works.
   
 ### Details and Assumptions
 * In the README.me file, show all the endpoints and args needed
 * How to test your code
 * (optional) Overall workflow if they want to join the team
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a user
 When they see the readme file
 Then how to use your endpoints and reuse your test cases
 ```

**Comment by rayichiu** [comment]
@brady800526 Should I update the readme file locally and issue a pull request or I just update it directly in GitHub?
